// This file is generated by Milease automatically

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using UnityEngine;

namespace Milease.CodeGen
{
    public static partial class GeneratedAccessors
    {
        internal static readonly Dictionary<(Type, string), object> getters = new Dictionary<(Type, string), object>()
        {
            [(typeof(UnityEngine.Transform), "position")] = new Func<UnityEngine.Transform, UnityEngine.Vector3>(_mil_generated_get_UnityEngine_Transform_position),
            [(typeof(UnityEngine.Transform), "localPosition")] = new Func<UnityEngine.Transform, UnityEngine.Vector3>(_mil_generated_get_UnityEngine_Transform_localPosition),
            [(typeof(UnityEngine.Transform), "localScale")] = new Func<UnityEngine.Transform, UnityEngine.Vector3>(_mil_generated_get_UnityEngine_Transform_localScale),
            [(typeof(UnityEngine.Transform), "eulerAngles")] = new Func<UnityEngine.Transform, UnityEngine.Vector3>(_mil_generated_get_UnityEngine_Transform_eulerAngles),
            [(typeof(UnityEngine.Transform), "localEulerAngles")] = new Func<UnityEngine.Transform, UnityEngine.Vector3>(_mil_generated_get_UnityEngine_Transform_localEulerAngles),
            [(typeof(UnityEngine.RectTransform), "anchoredPosition")] = new Func<UnityEngine.RectTransform, UnityEngine.Vector2>(_mil_generated_get_UnityEngine_RectTransform_anchoredPosition),
            [(typeof(UnityEngine.RectTransform), "sizeDelta")] = new Func<UnityEngine.RectTransform, UnityEngine.Vector2>(_mil_generated_get_UnityEngine_RectTransform_sizeDelta),
            [(typeof(UnityEngine.RectTransform), "anchorMin")] = new Func<UnityEngine.RectTransform, UnityEngine.Vector2>(_mil_generated_get_UnityEngine_RectTransform_anchorMin),
            [(typeof(UnityEngine.RectTransform), "anchorMax")] = new Func<UnityEngine.RectTransform, UnityEngine.Vector2>(_mil_generated_get_UnityEngine_RectTransform_anchorMax),
            [(typeof(UnityEngine.RectTransform), "pivot")] = new Func<UnityEngine.RectTransform, UnityEngine.Vector2>(_mil_generated_get_UnityEngine_RectTransform_pivot),
            [(typeof(UnityEngine.RectTransform), "position")] = new Func<UnityEngine.RectTransform, UnityEngine.Vector3>(_mil_generated_get_UnityEngine_RectTransform_position),
            [(typeof(UnityEngine.RectTransform), "localPosition")] = new Func<UnityEngine.RectTransform, UnityEngine.Vector3>(_mil_generated_get_UnityEngine_RectTransform_localPosition),
            [(typeof(UnityEngine.RectTransform), "localScale")] = new Func<UnityEngine.RectTransform, UnityEngine.Vector3>(_mil_generated_get_UnityEngine_RectTransform_localScale),
            [(typeof(UnityEngine.RectTransform), "eulerAngles")] = new Func<UnityEngine.RectTransform, UnityEngine.Vector3>(_mil_generated_get_UnityEngine_RectTransform_eulerAngles),
            [(typeof(UnityEngine.RectTransform), "localEulerAngles")] = new Func<UnityEngine.RectTransform, UnityEngine.Vector3>(_mil_generated_get_UnityEngine_RectTransform_localEulerAngles),
            [(typeof(UnityEngine.RectTransform), "anchoredPosition3D")] = new Func<UnityEngine.RectTransform, UnityEngine.Vector3>(_mil_generated_get_UnityEngine_RectTransform_anchoredPosition3D),
            [(typeof(UnityEngine.SpriteRenderer), "size")] = new Func<UnityEngine.SpriteRenderer, UnityEngine.Vector2>(_mil_generated_get_UnityEngine_SpriteRenderer_size),
            [(typeof(UnityEngine.SpriteRenderer), "color")] = new Func<UnityEngine.SpriteRenderer, UnityEngine.Color>(_mil_generated_get_UnityEngine_SpriteRenderer_color),
            [(typeof(UnityEngine.SpriteRenderer), "sortingOrder")] = new Func<UnityEngine.SpriteRenderer, System.Int32>(_mil_generated_get_UnityEngine_SpriteRenderer_sortingOrder),
            [(typeof(UnityEngine.Rigidbody), "velocity")] = new Func<UnityEngine.Rigidbody, UnityEngine.Vector3>(_mil_generated_get_UnityEngine_Rigidbody_velocity),
            [(typeof(UnityEngine.Rigidbody), "angularVelocity")] = new Func<UnityEngine.Rigidbody, UnityEngine.Vector3>(_mil_generated_get_UnityEngine_Rigidbody_angularVelocity),
            [(typeof(UnityEngine.Rigidbody2D), "velocity")] = new Func<UnityEngine.Rigidbody2D, UnityEngine.Vector2>(_mil_generated_get_UnityEngine_Rigidbody2D_velocity),
            [(typeof(UnityEngine.Rigidbody2D), "angularVelocity")] = new Func<UnityEngine.Rigidbody2D, System.Single>(_mil_generated_get_UnityEngine_Rigidbody2D_angularVelocity),
            [(typeof(UnityEngine.AudioSource), "volume")] = new Func<UnityEngine.AudioSource, System.Single>(_mil_generated_get_UnityEngine_AudioSource_volume),
            [(typeof(UnityEngine.AudioSource), "pitch")] = new Func<UnityEngine.AudioSource, System.Single>(_mil_generated_get_UnityEngine_AudioSource_pitch),
            [(typeof(UnityEngine.AudioSource), "spatialBlend")] = new Func<UnityEngine.AudioSource, System.Single>(_mil_generated_get_UnityEngine_AudioSource_spatialBlend),
            [(typeof(UnityEngine.AudioSource), "panStereo")] = new Func<UnityEngine.AudioSource, System.Single>(_mil_generated_get_UnityEngine_AudioSource_panStereo),
            [(typeof(UnityEngine.AudioSource), "dopplerLevel")] = new Func<UnityEngine.AudioSource, System.Single>(_mil_generated_get_UnityEngine_AudioSource_dopplerLevel),
            [(typeof(UnityEngine.CanvasGroup), "alpha")] = new Func<UnityEngine.CanvasGroup, System.Single>(_mil_generated_get_UnityEngine_CanvasGroup_alpha),
            [(typeof(UnityEngine.UI.Graphic), "color")] = new Func<UnityEngine.UI.Graphic, UnityEngine.Color>(_mil_generated_get_UnityEngine_UI_Graphic_color),
            [(typeof(UnityEngine.UI.Image), "color")] = new Func<UnityEngine.UI.Image, UnityEngine.Color>(_mil_generated_get_UnityEngine_UI_Image_color),
            [(typeof(UnityEngine.UI.Image), "fillAmount")] = new Func<UnityEngine.UI.Image, System.Single>(_mil_generated_get_UnityEngine_UI_Image_fillAmount),
            [(typeof(UnityEngine.UI.Text), "color")] = new Func<UnityEngine.UI.Text, UnityEngine.Color>(_mil_generated_get_UnityEngine_UI_Text_color),
            [(typeof(UnityEngine.UI.Text), "text")] = new Func<UnityEngine.UI.Text, System.String>(_mil_generated_get_UnityEngine_UI_Text_text),
            [(typeof(UnityEngine.UI.LayoutElement), "flexibleWidth")] = new Func<UnityEngine.UI.LayoutElement, System.Single>(_mil_generated_get_UnityEngine_UI_LayoutElement_flexibleWidth),
            [(typeof(UnityEngine.UI.LayoutElement), "flexibleHeight")] = new Func<UnityEngine.UI.LayoutElement, System.Single>(_mil_generated_get_UnityEngine_UI_LayoutElement_flexibleHeight),
            [(typeof(UnityEngine.UI.LayoutElement), "minWidth")] = new Func<UnityEngine.UI.LayoutElement, System.Single>(_mil_generated_get_UnityEngine_UI_LayoutElement_minWidth),
            [(typeof(UnityEngine.UI.LayoutElement), "minHeight")] = new Func<UnityEngine.UI.LayoutElement, System.Single>(_mil_generated_get_UnityEngine_UI_LayoutElement_minHeight),
            [(typeof(UnityEngine.UI.LayoutElement), "preferredWidth")] = new Func<UnityEngine.UI.LayoutElement, System.Single>(_mil_generated_get_UnityEngine_UI_LayoutElement_preferredWidth),
            [(typeof(UnityEngine.UI.LayoutElement), "preferredHeight")] = new Func<UnityEngine.UI.LayoutElement, System.Single>(_mil_generated_get_UnityEngine_UI_LayoutElement_preferredHeight),
            [(typeof(UnityEngine.UI.HorizontalLayoutGroup), "spacing")] = new Func<UnityEngine.UI.HorizontalLayoutGroup, System.Single>(_mil_generated_get_UnityEngine_UI_HorizontalLayoutGroup_spacing),
            [(typeof(UnityEngine.UI.VerticalLayoutGroup), "spacing")] = new Func<UnityEngine.UI.VerticalLayoutGroup, System.Single>(_mil_generated_get_UnityEngine_UI_VerticalLayoutGroup_spacing),
            [(typeof(UnityEngine.UI.Outline), "effectColor")] = new Func<UnityEngine.UI.Outline, UnityEngine.Color>(_mil_generated_get_UnityEngine_UI_Outline_effectColor),
            [(typeof(UnityEngine.UI.Outline), "effectDistance")] = new Func<UnityEngine.UI.Outline, UnityEngine.Vector2>(_mil_generated_get_UnityEngine_UI_Outline_effectDistance),
            [(typeof(UnityEngine.UI.ScrollRect), "horizontalNormalizedPosition")] = new Func<UnityEngine.UI.ScrollRect, System.Single>(_mil_generated_get_UnityEngine_UI_ScrollRect_horizontalNormalizedPosition),
            [(typeof(UnityEngine.UI.ScrollRect), "verticalNormalizedPosition")] = new Func<UnityEngine.UI.ScrollRect, System.Single>(_mil_generated_get_UnityEngine_UI_ScrollRect_verticalNormalizedPosition),
            [(typeof(UnityEngine.UI.Slider), "value")] = new Func<UnityEngine.UI.Slider, System.Single>(_mil_generated_get_UnityEngine_UI_Slider_value),
            [(typeof(UnityEngine.Material), "color")] = new Func<UnityEngine.Material, UnityEngine.Color>(_mil_generated_get_UnityEngine_Material_color),
        };
        
        internal static readonly Dictionary<(Type, string), object> setters = new Dictionary<(Type, string), object>()
        {
            [(typeof(UnityEngine.Transform), "position")] = new Action<UnityEngine.Transform, UnityEngine.Vector3>(_mil_generated_set_UnityEngine_Transform_position),
            [(typeof(UnityEngine.Transform), "localPosition")] = new Action<UnityEngine.Transform, UnityEngine.Vector3>(_mil_generated_set_UnityEngine_Transform_localPosition),
            [(typeof(UnityEngine.Transform), "localScale")] = new Action<UnityEngine.Transform, UnityEngine.Vector3>(_mil_generated_set_UnityEngine_Transform_localScale),
            [(typeof(UnityEngine.Transform), "eulerAngles")] = new Action<UnityEngine.Transform, UnityEngine.Vector3>(_mil_generated_set_UnityEngine_Transform_eulerAngles),
            [(typeof(UnityEngine.Transform), "localEulerAngles")] = new Action<UnityEngine.Transform, UnityEngine.Vector3>(_mil_generated_set_UnityEngine_Transform_localEulerAngles),
            [(typeof(UnityEngine.RectTransform), "anchoredPosition")] = new Action<UnityEngine.RectTransform, UnityEngine.Vector2>(_mil_generated_set_UnityEngine_RectTransform_anchoredPosition),
            [(typeof(UnityEngine.RectTransform), "sizeDelta")] = new Action<UnityEngine.RectTransform, UnityEngine.Vector2>(_mil_generated_set_UnityEngine_RectTransform_sizeDelta),
            [(typeof(UnityEngine.RectTransform), "anchorMin")] = new Action<UnityEngine.RectTransform, UnityEngine.Vector2>(_mil_generated_set_UnityEngine_RectTransform_anchorMin),
            [(typeof(UnityEngine.RectTransform), "anchorMax")] = new Action<UnityEngine.RectTransform, UnityEngine.Vector2>(_mil_generated_set_UnityEngine_RectTransform_anchorMax),
            [(typeof(UnityEngine.RectTransform), "pivot")] = new Action<UnityEngine.RectTransform, UnityEngine.Vector2>(_mil_generated_set_UnityEngine_RectTransform_pivot),
            [(typeof(UnityEngine.RectTransform), "position")] = new Action<UnityEngine.RectTransform, UnityEngine.Vector3>(_mil_generated_set_UnityEngine_RectTransform_position),
            [(typeof(UnityEngine.RectTransform), "localPosition")] = new Action<UnityEngine.RectTransform, UnityEngine.Vector3>(_mil_generated_set_UnityEngine_RectTransform_localPosition),
            [(typeof(UnityEngine.RectTransform), "localScale")] = new Action<UnityEngine.RectTransform, UnityEngine.Vector3>(_mil_generated_set_UnityEngine_RectTransform_localScale),
            [(typeof(UnityEngine.RectTransform), "eulerAngles")] = new Action<UnityEngine.RectTransform, UnityEngine.Vector3>(_mil_generated_set_UnityEngine_RectTransform_eulerAngles),
            [(typeof(UnityEngine.RectTransform), "localEulerAngles")] = new Action<UnityEngine.RectTransform, UnityEngine.Vector3>(_mil_generated_set_UnityEngine_RectTransform_localEulerAngles),
            [(typeof(UnityEngine.RectTransform), "anchoredPosition3D")] = new Action<UnityEngine.RectTransform, UnityEngine.Vector3>(_mil_generated_set_UnityEngine_RectTransform_anchoredPosition3D),
            [(typeof(UnityEngine.SpriteRenderer), "size")] = new Action<UnityEngine.SpriteRenderer, UnityEngine.Vector2>(_mil_generated_set_UnityEngine_SpriteRenderer_size),
            [(typeof(UnityEngine.SpriteRenderer), "color")] = new Action<UnityEngine.SpriteRenderer, UnityEngine.Color>(_mil_generated_set_UnityEngine_SpriteRenderer_color),
            [(typeof(UnityEngine.SpriteRenderer), "sortingOrder")] = new Action<UnityEngine.SpriteRenderer, System.Int32>(_mil_generated_set_UnityEngine_SpriteRenderer_sortingOrder),
            [(typeof(UnityEngine.Rigidbody), "velocity")] = new Action<UnityEngine.Rigidbody, UnityEngine.Vector3>(_mil_generated_set_UnityEngine_Rigidbody_velocity),
            [(typeof(UnityEngine.Rigidbody), "angularVelocity")] = new Action<UnityEngine.Rigidbody, UnityEngine.Vector3>(_mil_generated_set_UnityEngine_Rigidbody_angularVelocity),
            [(typeof(UnityEngine.Rigidbody2D), "velocity")] = new Action<UnityEngine.Rigidbody2D, UnityEngine.Vector2>(_mil_generated_set_UnityEngine_Rigidbody2D_velocity),
            [(typeof(UnityEngine.Rigidbody2D), "angularVelocity")] = new Action<UnityEngine.Rigidbody2D, System.Single>(_mil_generated_set_UnityEngine_Rigidbody2D_angularVelocity),
            [(typeof(UnityEngine.AudioSource), "volume")] = new Action<UnityEngine.AudioSource, System.Single>(_mil_generated_set_UnityEngine_AudioSource_volume),
            [(typeof(UnityEngine.AudioSource), "pitch")] = new Action<UnityEngine.AudioSource, System.Single>(_mil_generated_set_UnityEngine_AudioSource_pitch),
            [(typeof(UnityEngine.AudioSource), "spatialBlend")] = new Action<UnityEngine.AudioSource, System.Single>(_mil_generated_set_UnityEngine_AudioSource_spatialBlend),
            [(typeof(UnityEngine.AudioSource), "panStereo")] = new Action<UnityEngine.AudioSource, System.Single>(_mil_generated_set_UnityEngine_AudioSource_panStereo),
            [(typeof(UnityEngine.AudioSource), "dopplerLevel")] = new Action<UnityEngine.AudioSource, System.Single>(_mil_generated_set_UnityEngine_AudioSource_dopplerLevel),
            [(typeof(UnityEngine.CanvasGroup), "alpha")] = new Action<UnityEngine.CanvasGroup, System.Single>(_mil_generated_set_UnityEngine_CanvasGroup_alpha),
            [(typeof(UnityEngine.UI.Graphic), "color")] = new Action<UnityEngine.UI.Graphic, UnityEngine.Color>(_mil_generated_set_UnityEngine_UI_Graphic_color),
            [(typeof(UnityEngine.UI.Image), "color")] = new Action<UnityEngine.UI.Image, UnityEngine.Color>(_mil_generated_set_UnityEngine_UI_Image_color),
            [(typeof(UnityEngine.UI.Image), "fillAmount")] = new Action<UnityEngine.UI.Image, System.Single>(_mil_generated_set_UnityEngine_UI_Image_fillAmount),
            [(typeof(UnityEngine.UI.Text), "color")] = new Action<UnityEngine.UI.Text, UnityEngine.Color>(_mil_generated_set_UnityEngine_UI_Text_color),
            [(typeof(UnityEngine.UI.Text), "text")] = new Action<UnityEngine.UI.Text, System.String>(_mil_generated_set_UnityEngine_UI_Text_text),
            [(typeof(UnityEngine.UI.LayoutElement), "flexibleWidth")] = new Action<UnityEngine.UI.LayoutElement, System.Single>(_mil_generated_set_UnityEngine_UI_LayoutElement_flexibleWidth),
            [(typeof(UnityEngine.UI.LayoutElement), "flexibleHeight")] = new Action<UnityEngine.UI.LayoutElement, System.Single>(_mil_generated_set_UnityEngine_UI_LayoutElement_flexibleHeight),
            [(typeof(UnityEngine.UI.LayoutElement), "minWidth")] = new Action<UnityEngine.UI.LayoutElement, System.Single>(_mil_generated_set_UnityEngine_UI_LayoutElement_minWidth),
            [(typeof(UnityEngine.UI.LayoutElement), "minHeight")] = new Action<UnityEngine.UI.LayoutElement, System.Single>(_mil_generated_set_UnityEngine_UI_LayoutElement_minHeight),
            [(typeof(UnityEngine.UI.LayoutElement), "preferredWidth")] = new Action<UnityEngine.UI.LayoutElement, System.Single>(_mil_generated_set_UnityEngine_UI_LayoutElement_preferredWidth),
            [(typeof(UnityEngine.UI.LayoutElement), "preferredHeight")] = new Action<UnityEngine.UI.LayoutElement, System.Single>(_mil_generated_set_UnityEngine_UI_LayoutElement_preferredHeight),
            [(typeof(UnityEngine.UI.HorizontalLayoutGroup), "spacing")] = new Action<UnityEngine.UI.HorizontalLayoutGroup, System.Single>(_mil_generated_set_UnityEngine_UI_HorizontalLayoutGroup_spacing),
            [(typeof(UnityEngine.UI.VerticalLayoutGroup), "spacing")] = new Action<UnityEngine.UI.VerticalLayoutGroup, System.Single>(_mil_generated_set_UnityEngine_UI_VerticalLayoutGroup_spacing),
            [(typeof(UnityEngine.UI.Outline), "effectColor")] = new Action<UnityEngine.UI.Outline, UnityEngine.Color>(_mil_generated_set_UnityEngine_UI_Outline_effectColor),
            [(typeof(UnityEngine.UI.Outline), "effectDistance")] = new Action<UnityEngine.UI.Outline, UnityEngine.Vector2>(_mil_generated_set_UnityEngine_UI_Outline_effectDistance),
            [(typeof(UnityEngine.UI.ScrollRect), "horizontalNormalizedPosition")] = new Action<UnityEngine.UI.ScrollRect, System.Single>(_mil_generated_set_UnityEngine_UI_ScrollRect_horizontalNormalizedPosition),
            [(typeof(UnityEngine.UI.ScrollRect), "verticalNormalizedPosition")] = new Action<UnityEngine.UI.ScrollRect, System.Single>(_mil_generated_set_UnityEngine_UI_ScrollRect_verticalNormalizedPosition),
            [(typeof(UnityEngine.UI.Slider), "value")] = new Action<UnityEngine.UI.Slider, System.Single>(_mil_generated_set_UnityEngine_UI_Slider_value),
            [(typeof(UnityEngine.Material), "color")] = new Action<UnityEngine.Material, UnityEngine.Color>(_mil_generated_set_UnityEngine_Material_color),
        };

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_get_UnityEngine_Transform_position(UnityEngine.Transform o)
        {
            return o.position;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_Transform_position(UnityEngine.Transform o, UnityEngine.Vector3 v)
        {
            o.position = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_get_UnityEngine_Transform_localPosition(UnityEngine.Transform o)
        {
            return o.localPosition;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_Transform_localPosition(UnityEngine.Transform o, UnityEngine.Vector3 v)
        {
            o.localPosition = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_get_UnityEngine_Transform_localScale(UnityEngine.Transform o)
        {
            return o.localScale;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_Transform_localScale(UnityEngine.Transform o, UnityEngine.Vector3 v)
        {
            o.localScale = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_get_UnityEngine_Transform_eulerAngles(UnityEngine.Transform o)
        {
            return o.eulerAngles;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_Transform_eulerAngles(UnityEngine.Transform o, UnityEngine.Vector3 v)
        {
            o.eulerAngles = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_get_UnityEngine_Transform_localEulerAngles(UnityEngine.Transform o)
        {
            return o.localEulerAngles;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_Transform_localEulerAngles(UnityEngine.Transform o, UnityEngine.Vector3 v)
        {
            o.localEulerAngles = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector2 _mil_generated_get_UnityEngine_RectTransform_anchoredPosition(UnityEngine.RectTransform o)
        {
            return o.anchoredPosition;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_RectTransform_anchoredPosition(UnityEngine.RectTransform o, UnityEngine.Vector2 v)
        {
            o.anchoredPosition = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector2 _mil_generated_get_UnityEngine_RectTransform_sizeDelta(UnityEngine.RectTransform o)
        {
            return o.sizeDelta;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_RectTransform_sizeDelta(UnityEngine.RectTransform o, UnityEngine.Vector2 v)
        {
            o.sizeDelta = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector2 _mil_generated_get_UnityEngine_RectTransform_anchorMin(UnityEngine.RectTransform o)
        {
            return o.anchorMin;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_RectTransform_anchorMin(UnityEngine.RectTransform o, UnityEngine.Vector2 v)
        {
            o.anchorMin = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector2 _mil_generated_get_UnityEngine_RectTransform_anchorMax(UnityEngine.RectTransform o)
        {
            return o.anchorMax;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_RectTransform_anchorMax(UnityEngine.RectTransform o, UnityEngine.Vector2 v)
        {
            o.anchorMax = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector2 _mil_generated_get_UnityEngine_RectTransform_pivot(UnityEngine.RectTransform o)
        {
            return o.pivot;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_RectTransform_pivot(UnityEngine.RectTransform o, UnityEngine.Vector2 v)
        {
            o.pivot = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_get_UnityEngine_RectTransform_position(UnityEngine.RectTransform o)
        {
            return o.position;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_RectTransform_position(UnityEngine.RectTransform o, UnityEngine.Vector3 v)
        {
            o.position = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_get_UnityEngine_RectTransform_localPosition(UnityEngine.RectTransform o)
        {
            return o.localPosition;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_RectTransform_localPosition(UnityEngine.RectTransform o, UnityEngine.Vector3 v)
        {
            o.localPosition = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_get_UnityEngine_RectTransform_localScale(UnityEngine.RectTransform o)
        {
            return o.localScale;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_RectTransform_localScale(UnityEngine.RectTransform o, UnityEngine.Vector3 v)
        {
            o.localScale = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_get_UnityEngine_RectTransform_eulerAngles(UnityEngine.RectTransform o)
        {
            return o.eulerAngles;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_RectTransform_eulerAngles(UnityEngine.RectTransform o, UnityEngine.Vector3 v)
        {
            o.eulerAngles = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_get_UnityEngine_RectTransform_localEulerAngles(UnityEngine.RectTransform o)
        {
            return o.localEulerAngles;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_RectTransform_localEulerAngles(UnityEngine.RectTransform o, UnityEngine.Vector3 v)
        {
            o.localEulerAngles = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_get_UnityEngine_RectTransform_anchoredPosition3D(UnityEngine.RectTransform o)
        {
            return o.anchoredPosition3D;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_RectTransform_anchoredPosition3D(UnityEngine.RectTransform o, UnityEngine.Vector3 v)
        {
            o.anchoredPosition3D = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector2 _mil_generated_get_UnityEngine_SpriteRenderer_size(UnityEngine.SpriteRenderer o)
        {
            return o.size;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_SpriteRenderer_size(UnityEngine.SpriteRenderer o, UnityEngine.Vector2 v)
        {
            o.size = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Color _mil_generated_get_UnityEngine_SpriteRenderer_color(UnityEngine.SpriteRenderer o)
        {
            return o.color;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_SpriteRenderer_color(UnityEngine.SpriteRenderer o, UnityEngine.Color v)
        {
            o.color = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Int32 _mil_generated_get_UnityEngine_SpriteRenderer_sortingOrder(UnityEngine.SpriteRenderer o)
        {
            return o.sortingOrder;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_SpriteRenderer_sortingOrder(UnityEngine.SpriteRenderer o, System.Int32 v)
        {
            o.sortingOrder = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_get_UnityEngine_Rigidbody_velocity(UnityEngine.Rigidbody o)
        {
            return o.velocity;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_Rigidbody_velocity(UnityEngine.Rigidbody o, UnityEngine.Vector3 v)
        {
            o.velocity = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_get_UnityEngine_Rigidbody_angularVelocity(UnityEngine.Rigidbody o)
        {
            return o.angularVelocity;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_Rigidbody_angularVelocity(UnityEngine.Rigidbody o, UnityEngine.Vector3 v)
        {
            o.angularVelocity = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector2 _mil_generated_get_UnityEngine_Rigidbody2D_velocity(UnityEngine.Rigidbody2D o)
        {
            return o.velocity;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_Rigidbody2D_velocity(UnityEngine.Rigidbody2D o, UnityEngine.Vector2 v)
        {
            o.velocity = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_Rigidbody2D_angularVelocity(UnityEngine.Rigidbody2D o)
        {
            return o.angularVelocity;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_Rigidbody2D_angularVelocity(UnityEngine.Rigidbody2D o, System.Single v)
        {
            o.angularVelocity = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_AudioSource_volume(UnityEngine.AudioSource o)
        {
            return o.volume;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_AudioSource_volume(UnityEngine.AudioSource o, System.Single v)
        {
            o.volume = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_AudioSource_pitch(UnityEngine.AudioSource o)
        {
            return o.pitch;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_AudioSource_pitch(UnityEngine.AudioSource o, System.Single v)
        {
            o.pitch = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_AudioSource_spatialBlend(UnityEngine.AudioSource o)
        {
            return o.spatialBlend;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_AudioSource_spatialBlend(UnityEngine.AudioSource o, System.Single v)
        {
            o.spatialBlend = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_AudioSource_panStereo(UnityEngine.AudioSource o)
        {
            return o.panStereo;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_AudioSource_panStereo(UnityEngine.AudioSource o, System.Single v)
        {
            o.panStereo = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_AudioSource_dopplerLevel(UnityEngine.AudioSource o)
        {
            return o.dopplerLevel;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_AudioSource_dopplerLevel(UnityEngine.AudioSource o, System.Single v)
        {
            o.dopplerLevel = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_CanvasGroup_alpha(UnityEngine.CanvasGroup o)
        {
            return o.alpha;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_CanvasGroup_alpha(UnityEngine.CanvasGroup o, System.Single v)
        {
            o.alpha = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Color _mil_generated_get_UnityEngine_UI_Graphic_color(UnityEngine.UI.Graphic o)
        {
            return o.color;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_Graphic_color(UnityEngine.UI.Graphic o, UnityEngine.Color v)
        {
            o.color = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Color _mil_generated_get_UnityEngine_UI_Image_color(UnityEngine.UI.Image o)
        {
            return o.color;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_Image_color(UnityEngine.UI.Image o, UnityEngine.Color v)
        {
            o.color = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_UI_Image_fillAmount(UnityEngine.UI.Image o)
        {
            return o.fillAmount;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_Image_fillAmount(UnityEngine.UI.Image o, System.Single v)
        {
            o.fillAmount = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Color _mil_generated_get_UnityEngine_UI_Text_color(UnityEngine.UI.Text o)
        {
            return o.color;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_Text_color(UnityEngine.UI.Text o, UnityEngine.Color v)
        {
            o.color = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.String _mil_generated_get_UnityEngine_UI_Text_text(UnityEngine.UI.Text o)
        {
            return o.text;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_Text_text(UnityEngine.UI.Text o, System.String v)
        {
            o.text = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_UI_LayoutElement_flexibleWidth(UnityEngine.UI.LayoutElement o)
        {
            return o.flexibleWidth;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_LayoutElement_flexibleWidth(UnityEngine.UI.LayoutElement o, System.Single v)
        {
            o.flexibleWidth = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_UI_LayoutElement_flexibleHeight(UnityEngine.UI.LayoutElement o)
        {
            return o.flexibleHeight;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_LayoutElement_flexibleHeight(UnityEngine.UI.LayoutElement o, System.Single v)
        {
            o.flexibleHeight = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_UI_LayoutElement_minWidth(UnityEngine.UI.LayoutElement o)
        {
            return o.minWidth;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_LayoutElement_minWidth(UnityEngine.UI.LayoutElement o, System.Single v)
        {
            o.minWidth = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_UI_LayoutElement_minHeight(UnityEngine.UI.LayoutElement o)
        {
            return o.minHeight;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_LayoutElement_minHeight(UnityEngine.UI.LayoutElement o, System.Single v)
        {
            o.minHeight = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_UI_LayoutElement_preferredWidth(UnityEngine.UI.LayoutElement o)
        {
            return o.preferredWidth;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_LayoutElement_preferredWidth(UnityEngine.UI.LayoutElement o, System.Single v)
        {
            o.preferredWidth = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_UI_LayoutElement_preferredHeight(UnityEngine.UI.LayoutElement o)
        {
            return o.preferredHeight;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_LayoutElement_preferredHeight(UnityEngine.UI.LayoutElement o, System.Single v)
        {
            o.preferredHeight = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_UI_HorizontalLayoutGroup_spacing(UnityEngine.UI.HorizontalLayoutGroup o)
        {
            return o.spacing;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_HorizontalLayoutGroup_spacing(UnityEngine.UI.HorizontalLayoutGroup o, System.Single v)
        {
            o.spacing = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_UI_VerticalLayoutGroup_spacing(UnityEngine.UI.VerticalLayoutGroup o)
        {
            return o.spacing;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_VerticalLayoutGroup_spacing(UnityEngine.UI.VerticalLayoutGroup o, System.Single v)
        {
            o.spacing = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Color _mil_generated_get_UnityEngine_UI_Outline_effectColor(UnityEngine.UI.Outline o)
        {
            return o.effectColor;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_Outline_effectColor(UnityEngine.UI.Outline o, UnityEngine.Color v)
        {
            o.effectColor = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector2 _mil_generated_get_UnityEngine_UI_Outline_effectDistance(UnityEngine.UI.Outline o)
        {
            return o.effectDistance;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_Outline_effectDistance(UnityEngine.UI.Outline o, UnityEngine.Vector2 v)
        {
            o.effectDistance = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_UI_ScrollRect_horizontalNormalizedPosition(UnityEngine.UI.ScrollRect o)
        {
            return o.horizontalNormalizedPosition;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_ScrollRect_horizontalNormalizedPosition(UnityEngine.UI.ScrollRect o, System.Single v)
        {
            o.horizontalNormalizedPosition = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_UI_ScrollRect_verticalNormalizedPosition(UnityEngine.UI.ScrollRect o)
        {
            return o.verticalNormalizedPosition;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_ScrollRect_verticalNormalizedPosition(UnityEngine.UI.ScrollRect o, System.Single v)
        {
            o.verticalNormalizedPosition = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static System.Single _mil_generated_get_UnityEngine_UI_Slider_value(UnityEngine.UI.Slider o)
        {
            return o.value;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_UI_Slider_value(UnityEngine.UI.Slider o, System.Single v)
        {
            o.value = v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Color _mil_generated_get_UnityEngine_Material_color(UnityEngine.Material o)
        {
            return o.color;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void _mil_generated_set_UnityEngine_Material_color(UnityEngine.Material o, UnityEngine.Color v)
        {
            o.color = v;
        }

    }
}
