// This file is generated by Milease automatically

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using UnityEngine;

namespace Milease.CodeGen
{
    public delegate E DeltaCalculateFunction<E>(E start, E to);
    public delegate E CalculateFunction<E>(E start, E delta, float progress);
    public delegate E OffsetCalculateFunction<E>(E start, E delta, float progress, E offset);
    public static partial class GeneratedCalculation
    {
        internal static readonly Dictionary<Type, object> deltaCalculateFunctions = new Dictionary<Type, object>()
        {
            [typeof(UnityEngine.Color)] = new DeltaCalculateFunction<UnityEngine.Color>(_mil_generated_calc_delta),
            [typeof(UnityEngine.Vector3)] = new DeltaCalculateFunction<UnityEngine.Vector3>(_mil_generated_calc_delta),
            [typeof(UnityEngine.Vector2)] = new DeltaCalculateFunction<UnityEngine.Vector2>(_mil_generated_calc_delta),
            [typeof(UnityEngine.Vector4)] = new DeltaCalculateFunction<UnityEngine.Vector4>(_mil_generated_calc_delta),
            [typeof(ushort)] = new DeltaCalculateFunction<ushort>(_mil_generated_calc_delta),
            [typeof(short)] = new DeltaCalculateFunction<short>(_mil_generated_calc_delta),
            [typeof(uint)] = new DeltaCalculateFunction<uint>(_mil_generated_calc_delta),
            [typeof(int)] = new DeltaCalculateFunction<int>(_mil_generated_calc_delta),
            [typeof(ulong)] = new DeltaCalculateFunction<ulong>(_mil_generated_calc_delta),
            [typeof(long)] = new DeltaCalculateFunction<long>(_mil_generated_calc_delta),
            [typeof(float)] = new DeltaCalculateFunction<float>(_mil_generated_calc_delta),
            [typeof(double)] = new DeltaCalculateFunction<double>(_mil_generated_calc_delta),
            [typeof(string)] = new DeltaCalculateFunction<string>(_mil_generated_calc_delta),
            [typeof(object)] = new DeltaCalculateFunction<object>(_mil_generated_calc_delta)
        };
        
        internal static readonly Dictionary<Type, object> calculateFunctions = new Dictionary<Type, object>()
        {
            [typeof(UnityEngine.Color)] = new CalculateFunction<UnityEngine.Color>(_mil_generated_calc),
            [typeof(UnityEngine.Vector3)] = new CalculateFunction<UnityEngine.Vector3>(_mil_generated_calc),
            [typeof(UnityEngine.Vector2)] = new CalculateFunction<UnityEngine.Vector2>(_mil_generated_calc),
            [typeof(UnityEngine.Vector4)] = new CalculateFunction<UnityEngine.Vector4>(_mil_generated_calc),
            [typeof(ushort)] = new CalculateFunction<ushort>(_mil_generated_calc),
            [typeof(short)] = new CalculateFunction<short>(_mil_generated_calc),
            [typeof(uint)] = new CalculateFunction<uint>(_mil_generated_calc),
            [typeof(int)] = new CalculateFunction<int>(_mil_generated_calc),
            [typeof(ulong)] = new CalculateFunction<ulong>(_mil_generated_calc),
            [typeof(long)] = new CalculateFunction<long>(_mil_generated_calc),
            [typeof(float)] = new CalculateFunction<float>(_mil_generated_calc),
            [typeof(double)] = new CalculateFunction<double>(_mil_generated_calc),
            [typeof(string)] = new CalculateFunction<string>(_mil_generated_calc),
            [typeof(object)] = new CalculateFunction<object>(_mil_generated_calc)
        };

        internal static readonly Dictionary<Type, object> offsetCalculateFunctions = new Dictionary<Type, object>()
        {
            [typeof(UnityEngine.Color)] = new OffsetCalculateFunction<UnityEngine.Color>(_mil_generated_calc_offset),
            [typeof(UnityEngine.Vector3)] = new OffsetCalculateFunction<UnityEngine.Vector3>(_mil_generated_calc_offset),
            [typeof(UnityEngine.Vector2)] = new OffsetCalculateFunction<UnityEngine.Vector2>(_mil_generated_calc_offset),
            [typeof(UnityEngine.Vector4)] = new OffsetCalculateFunction<UnityEngine.Vector4>(_mil_generated_calc_offset),
            [typeof(ushort)] = new OffsetCalculateFunction<ushort>(_mil_generated_calc_offset),
            [typeof(short)] = new OffsetCalculateFunction<short>(_mil_generated_calc_offset),
            [typeof(uint)] = new OffsetCalculateFunction<uint>(_mil_generated_calc_offset),
            [typeof(int)] = new OffsetCalculateFunction<int>(_mil_generated_calc_offset),
            [typeof(ulong)] = new OffsetCalculateFunction<ulong>(_mil_generated_calc_offset),
            [typeof(long)] = new OffsetCalculateFunction<long>(_mil_generated_calc_offset),
            [typeof(float)] = new OffsetCalculateFunction<float>(_mil_generated_calc_offset),
            [typeof(double)] = new OffsetCalculateFunction<double>(_mil_generated_calc_offset),
            [typeof(string)] = new OffsetCalculateFunction<string>(_mil_generated_calc_offset),
            [typeof(object)] = new OffsetCalculateFunction<object>(_mil_generated_calc_offset)
        };
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Color _mil_generated_calc(UnityEngine.Color a, UnityEngine.Color b, float p)
        {
            return a + b * p;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Color _mil_generated_calc_offset(UnityEngine.Color a, UnityEngine.Color b, float p, UnityEngine.Color o)
        {
            return a + b * p + o;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Color _mil_generated_calc_delta(UnityEngine.Color a, UnityEngine.Color b)
        {
            return b - a;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_calc(UnityEngine.Vector3 a, UnityEngine.Vector3 b, float p)
        {
            return a + b * p;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_calc_offset(UnityEngine.Vector3 a, UnityEngine.Vector3 b, float p, UnityEngine.Vector3 o)
        {
            return a + b * p + o;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector3 _mil_generated_calc_delta(UnityEngine.Vector3 a, UnityEngine.Vector3 b)
        {
            return b - a;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector2 _mil_generated_calc(UnityEngine.Vector2 a, UnityEngine.Vector2 b, float p)
        {
            return a + b * p;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector2 _mil_generated_calc_offset(UnityEngine.Vector2 a, UnityEngine.Vector2 b, float p, UnityEngine.Vector2 o)
        {
            return a + b * p + o;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector2 _mil_generated_calc_delta(UnityEngine.Vector2 a, UnityEngine.Vector2 b)
        {
            return b - a;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector4 _mil_generated_calc(UnityEngine.Vector4 a, UnityEngine.Vector4 b, float p)
        {
            return a + b * p;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector4 _mil_generated_calc_offset(UnityEngine.Vector4 a, UnityEngine.Vector4 b, float p, UnityEngine.Vector4 o)
        {
            return a + b * p + o;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityEngine.Vector4 _mil_generated_calc_delta(UnityEngine.Vector4 a, UnityEngine.Vector4 b)
        {
            return b - a;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort _mil_generated_calc(ushort a, ushort b, float p)
        {
            return (ushort)(a + b * p);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort _mil_generated_calc_offset(ushort a, ushort b, float p, ushort o)
        {
            return (ushort)(a + b * p + o);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ushort _mil_generated_calc_delta(ushort a, ushort b)
        {
            return (ushort)(b - a);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short _mil_generated_calc(short a, short b, float p)
        {
            return (short)(a + b * p);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short _mil_generated_calc_offset(short a, short b, float p, short o)
        {
            return (short)(a + b * p + o);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static short _mil_generated_calc_delta(short a, short b)
        {
            return (short)(b - a);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint _mil_generated_calc(uint a, uint b, float p)
        {
            return (uint)(a + b * p);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint _mil_generated_calc_offset(uint a, uint b, float p, uint o)
        {
            return (uint)(a + b * p + o);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint _mil_generated_calc_delta(uint a, uint b)
        {
            return (b - a);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int _mil_generated_calc(int a, int b, float p)
        {
            return (int)(a + b * p);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int _mil_generated_calc_offset(int a, int b, float p, int o)
        {
            return (int)(a + b * p + o);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int _mil_generated_calc_delta(int a, int b)
        {
            return b - a;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong _mil_generated_calc(ulong a, ulong b, float p)
        {
            return (ulong)(a + b * p);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong _mil_generated_calc_offset(ulong a, ulong b, float p, ulong o)
        {
            return (ulong)(a + b * p + o);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ulong _mil_generated_calc_delta(ulong a, ulong b)
        {
            return b - a;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static long _mil_generated_calc(long a, long b, float p)
        {
            return (long)(a + b * p);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static long _mil_generated_calc_offset(long a, long b, float p, long o)
        {
            return (long)(a + b * p + o);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static long _mil_generated_calc_delta(long a, long b)
        {
            return b - a;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float _mil_generated_calc(float a, float b, float p)
        {
            return a + b * p;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float _mil_generated_calc_offset(float a, float b, float p, float o)
        {
            return a + b * p + o;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float _mil_generated_calc_delta(float a, float b)
        {
            return b - a;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static double _mil_generated_calc(double a, double b, float p)
        {
            return a + b * p;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static double _mil_generated_calc_offset(double a, double b, float p, double o)
        {
            return a + b * p + o;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static double _mil_generated_calc_delta(double a, double b)
        {
            return b - a;
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string _mil_generated_calc(string a, string b, float p)
        {
            return b?.Substring(0, (int)(b.Length * p));
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string _mil_generated_calc_offset(string a, string b, float p, string o)
        {
            return o + b?.Substring(0, (int)(b.Length * p));
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string _mil_generated_calc_delta(string a, string b)
        {
            return b;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static object _mil_generated_calc(object a, object b, float p)
        {
            return (p >= 1f ? b : a);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static object _mil_generated_calc_offset(object a, object b, float p, object o)
        {
            return (p >= 1f ? b : a);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static object _mil_generated_calc_delta(object a, object b)
        {
            return b;
        }
    }
}
